#!/bin/bash

git clone https://github.com/torch/distro.git ~/torch --recursive

# dependencies are installed in apt.txt, we just run the install.sh script
cd ~/torch
./install.sh -b

source ~/.bashrc

# Install most things using luarocks
luarocks install torch
luarocks install nn
luarocks install optim
luarocks install lua-cjson

# We need to install torch-hdf5 from GitHub
git clone https://github.com/deepmind/torch-hdf5
cd torch-hdf5
luarocks make hdf5-0-0.rockspec
